module.exports = {
  STORAGE_KEY: 'key',
  HEARTBEAT_PERIOD: 'preiod',
  UPDATE_INPUT: 'UPDATE_INPUT',
  UPDATE_SIZE: 'UPDATE_SIZE',
  MERGE_BATTERY_INFO: 'MERGE_BATTERY_INFO',
  TOGGLE_TAB: 'TOGGLE_TAB',
};